### ISSUE TITLE
Method 'Create' in type 'Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransportFactory' [...] does not have an implementation.

### ISSUE THREAD

**Issue by Kimserey** [OrleansContrib/OrleansDashboard#168]
I added the dashboard to my project with `.Dashboard()` on the `SiloHostBuilder` and am seeing the following exception printed in the logs:

```
[00:01:30.139 ERR] OrleansDashboard.Dashboard: System.TypeLoadException: Method 'Create' in type 'Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransportFactory' from assembly 'Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at Microsoft.AspNetCore.Hosting.WebHostBuilderLibuvExtensions.<>c.<UseLibuv>b__0_0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at OrleansDashboard.Dashboard.Execute(CancellationToken cancellationToken)
```

The dashboard is not accessible but I am not sure if this error is the one preventing it to boot.

Setup: 
- .NET Core app 2.1
- Orleans 2.0.x

**Comment by Kimserey** [comment]
Adding the nuget package `Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv 2.1.2` fixes it. But I can't seem to replicate on a fresh project.

**Comment by Kimserey** [comment]
I'll close this as it seems to work fine. I'll reopen if I have a concrete sample project with the error.
Thank you.
