### ISSUE TITLE
Unhandled exception in GrainProfiler causes silo fail

### ISSUE THREAD

**Issue by DixonDs** [OrleansContrib/OrleansDashboard#18]
This is the last log before the silo crashed:
```
[2016-11-07 11:01:06.930 GMT    72	ERROR  	100324	Silo	XXX.XXX.XXX.XXX:11111]	!!!!!!!!!! Called DomainUnobservedExceptionHandler with context Name:RdRuntime
There are no context policies.
.	
Exc level 0: System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at OrleansDashboard.GrainProfiler.ProcessStats(Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Exc level 1: System.TimeoutException: Response did not arrive on time in 00:00:30 for message: Request SXXX.XXX.XXX.XXX:11111:216212275ProviderManagerSystemTarget@S00000013->SXXX.XXX.XXX.XXX:11111:216212275*grn/FFE8F7B3/00000000@c4d2e8a5 #18592: global::OrleansDashboard.IDashboardGrain:SubmitTracing(). Target History is: <SXXX.XXX.XXX.XXX:11111:216212275:*grn/FFE8F7B3/00000000:@c4d2e8a5>.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OrleansDashboard.GrainProfiler.<>c__DisplayClass14_0.<<ProcessStats>b__0>d.MoveNext()
```

It seems that unhandled exception in `GrainProfiler.ProcessStats` called on timer caused the whole thing to crash

**Comment by richorama** [comment]
ok, I'll take a look, thanks!

**Comment by richorama** [comment]
@DixonDs did you have a particularly large number of silos/grains/uptime?

**Comment by DixonDs** [comment]
Yes, we had several thousands of activations at the time. So basically we have two issues here - the timeout itself and the silo crash subsequently instead of just ignoring the error. The later one is more critical, we had to disable the dashboard until it is solved.

**Comment by richorama** [comment]
I have added an exception handler and logging with the latest release (1.3.1) : on this commit https://github.com/OrleansContrib/OrleansDashboard/commit/ebddb5e84e3f2a2a7bdfbd547084d7349e809f27
