### ISSUE TITLE
SerializationException

### ISSUE THREAD

**Issue by kapcsandi** [OrleansContrib/OrleansDashboard#218]
I've upgraded from 2.1.3 to 2.2.5 the OrleansDashboard package in my silo project. After this, the silo deployment failed with serialization errors, like:

```
   [12:29:54 ERR] Exception trying to process 2861 bytes from endpoint 10.244.1.64:37701
System.Runtime.Serialization.SerializationException: Unsupported type 'OrleansDashboard.Client.Model.SiloDetails' encountered. Perhaps you need to mark it [Serializable] or define a custom serializer for it?
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeArray(Type resultType, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at OrleansDashboard.Client.Model.OrleansCodeGenOrleansDashboard_Client_Model_DashboardCountersSerializer.Deserializer(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeImmutable[T](Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
   at Orleans.Serialization.SerializationManager.Deserialize(Type t, IBinaryTokenStreamReader stream)
   at Orleans.Runtime.IncomingMessageBuffer.TryDecodeMessage(Message& msg)
   at Orleans.Runtime.Messaging.IncomingMessageAcceptor.ReceiveCallbackContext.ProcessReceived(SocketAsyncEventArgs e)
```

The workaround that solved this was scaling down the silos to 0 then scaling up again.

**Comment by richorama** [comment]
Hi @kapcsandi, thanks for reporting this error.

Do you think this is a bug in the dashboard, or is it a side effect of an upgrade process?

Is the error reproducible in any way?

**Comment by kapcsandi** [comment]
In my setup, there are 3 silos in a k8s cluster deployed as a stateful set. 
The deployment flow was: silo-2 was replaced w/ the new version, the other silos (silo-0 & silo-1) are waiting until silo-2 comes up and join the cluster. 
I think the grain state object (Client.Model.SiloDetails) tried to migrate to the new silo, but it failed because of the missing serialization annotation.
However I didn't try to reproduce the error.

**Comment by SebastianStehle** [comment]
I am going to close it. It is just too old.
