### ISSUE TITLE
Unable to resolve service for type 'Orleans.IReminderTable' while attempting to activate 'OrleansDashboard.DashboardRemindersGrain'

### ISSUE THREAD

**Issue by bddckr** [OrleansContrib/OrleansDashboard#246]
Looks like Dashboard needs to use `IReminderTableGrain` in Orleans 2.4.0+ now? [Here](https://github.com/dotnet/orleans/pull/5714)'s the PR that changed it AFAICS.
```
Orleans.Runtime.Dispatcher: Error: Error creating activation for OrleansDashboard.DashboardRemindersGrain. Message NewPlacement Request S127.0.0.1:11111:303392341*cli/514411b1@61a3b394->S127.0.0.1:11111:303392341*grn/D58C58F1/00000000@a23714bb #2639: 

System.InvalidOperationException: Unable to resolve service for type 'Orleans.IReminderTable' while attempting to activate 'OrleansDashboard.DashboardRemindersGrain'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Orleans.Runtime.DefaultGrainActivator.Create(IGrainActivationContext context)
   at Orleans.Runtime.GrainCreator.CreateGrainInstance(IGrainActivationContext context)
   at Orleans.Runtime.Catalog.CreateGrainInstance(String grainTypeName, ActivationData data, String genericArguments)
   at Orleans.Runtime.Catalog.SetupActivationInstance(ActivationData result, String grainType, String genericArguments)
   at Orleans.Runtime.Catalog.GetOrCreateActivation(ActivationAddress address, Boolean newPlacement, String grainType, String genericArguments, Dictionary`2 requestContextData, Task& activatedPromise)
   at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message)
```

**Comment by SebastianStehle** [comment]
Do you have no ReminderTable registered?

**Comment by bddckr** [comment]
🤦‍♂ Sorry! I did, but in my working copy I removed the reminder service!

I commented on the PR.
