### ISSUE TITLE
Exception in TraceHistory: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by angerico-carino** [OrleansContrib/OrleansDashboard#255]
The latest code is throwing the following:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at OrleansDashboard.Metrics.History.TraceHistory.Add(DateTime now, String siloAddress, SiloGrainTraceEntry[] grainTrace)
   at OrleansDashboard.DashboardGrain.SubmitTracing(String siloAddress, Immutable`1 grainTrace)
   at OrleansDashboard.Client.OrleansCodeGenDashboardGrainMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request)
   at Orleans.Runtime.GrainMethodInvoker.Invoke()
   at OrleansDashboard.Metrics.GrainProfilerFilter.Invoke(IIncomingGrainCallContext context)
   at Orleans.Runtime.GrainMethodInvoker.Invoke()
   at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message)
```

I assume it is because there is an iteration over `allGrainTrace` in here: https://github.com/OrleansContrib/OrleansDashboard/blob/master/OrleansDashboard/Metrics/History/TraceHistory.cs#L96
And there is a snippet that adds to `allMethods` in here:
https://github.com/OrleansContrib/OrleansDashboard/blob/master/OrleansDashboard/Metrics/History/TraceHistory.cs#L100
But the problem is that `allGrainTrace` is executed in a deferred manner and it needs `allMethods` in its iteration, which can be modified within the loop... thus causing the exception above.

**Comment by SebastianStehle** [comment]
True, it makes no sense. There should be two loops.
