### ISSUE TITLE
DisposeAsync not handled properly in Orleans 3.2.2

### ISSUE THREAD

**Issue by DiAifU** [OrleansContrib/OrleansDashboard#295]
Hi,

I just tried updating to Orleans 3.2.2 from 3.1.6, and I am getting errors during silo shutdown with this exception :

```log
Application: eZ.Orleans.Silo.exe
CoreCLR Version: 4.700.20.11803
.NET Core Version: 3.1.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: 'eZ.M7Service.Grains.Utils.ObjectsSaver' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Orleans.Runtime.Catalog.DestroyActivation(ActivationData activationData, CancellationToken ct)
   at Orleans.Runtime.Catalog.<>c__DisplayClass75_0.<<DeactivateActivation>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

It was working fine before. Has anything changed in 3.2.2 or any recent versions regarding DisposeAsync ?

Thanks for your help !

**Comment by DiAifU** [comment]
This issue was for Orleans repo, closing this.
