### ISSUE TITLE
System.MissingMemberException: The server factory could not be located for the given input: Nowin

### ISSUE THREAD

**Issue by kianmeng-aft** [OrleansContrib/OrleansDashboard#30]
Hi,

I have implement Orleans Dashboard for quite sometime and everything is working fine (the last working version is 1.3.4) but recently I upgraded my project to VS2017 and I face the following error
`System.MissingMemberException: The server factory could not be located for the given input: Nowin`

cant seems to find any solution online, please advice.

I am using the  programmatic configuration:
```
var siloHost = new SiloHost(...);
siloHost.InitializeOrleansSilo();
siloHost.Config.Globals.RegisterDashboard(); // port, username and password can also be supplied
siloHost.StartOrleansSilo();
```

# Error
```
[16:56:49 INF] Runtime - 127.0.0.1:11111: Loaded provider of type OrleansDashboard.Dashboard Name=Dashboard
[2016-12-20 08:56:49.862 GMT    22      INFO    103102  ProviderLoader/IBootstrapProvider       127.0.0.1:11111]
Loaded provider of type OrleansDashboard.Dashboard Name=Dashboard
[16:56:49 INF] Runtime - 127.0.0.1:11111: Calling Init for IBootstrapProvider classes
[2016-12-20 08:56:49.873 GMT    22      INFO    100437  BootstrapProviderManager        127.0.0.1:11111]        Calling Init for IBootstrapProvider classes
[16:56:49 ERR] Provider - 127.0.0.1:11111: System.MissingMemberException: The server factory could not be located for the given input: Nowin
   at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveServerFactory(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at OrleansDashboard.Dashboard.<Init>d__8.MoveNext()
OrleansHost.exe Error: 0 : [2016-12-20 08:56:49.939 GMT    22   ERROR   10001   Dashboard       127.0.0.1:11111]
!!!!!!!!!! System.MissingMemberException: The server factory could not be located for the given input: Nowin
   at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveServerFactory(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at OrleansDashboard.Dashboard.<Init>d__8.MoveNext()
[2016-12-20 08:56:49.939 GMT    22      ERROR   10001   Dashboard       127.0.0.1:11111]        !!!!!!!!!! System.MissingMemberException: The server factory could not be located for the given input: Nowin
   at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveServerFactory(StartContext context)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at OrleansDashboard.Dashboard.<Init>d__8.MoveNext()
[16:56:50 INF] Runtime - 127.0.0.1:11111: SystemStatus=Running
[16:56:50 INF] Runtime - 127.0.0.1:11111: Starting AsyncAgent Runtime.Messaging.GatewayAcceptor on managed thread 28
OrleansHost.exe Information: 0 : [2016-12-20 08:56:50.042 GMT     1     INFO    100294  SystemStatus    127.0.0.1:11111]        SystemStatus=Running
```

**Comment by richorama** [comment]
Thanks for reporting the problem.

I can't understand why an upgrade to VS2017 would cause this, but it looks like the `Nowin` library cannot be found.

Are you attempting to use .NET core?

Can you confirm that the Nowin assembly in in the bin folder?
