### ISSUE TITLE
Dashboard crashed occationally

### ISSUE THREAD

**Issue by wangjia184** [OrleansContrib/OrleansDashboard#312]
```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at OrleansDashboard.DashboardTelemetryConsumer.Flush()
   at OrleansDashboard.DashboardTelemetryConsumer.<.ctor>b__8_0(Object x)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by SebastianStehle** [comment]
I have seen it as well. I will provide a fix soon. It is a race condition.
