### ISSUE TITLE
System.OverflowException: TimeSpan overflowed because the duration is too long

### ISSUE THREAD

**Issue by mhertis** [OrleansContrib/OrleansDashboard#316]
Our silo is crashing with the following exception in Windows Event Log. 

CoreCLR Version: 4.700.19.56402
.NET Core Version: 3.1.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OverflowException: TimeSpan overflowed because the duration is too long.
   at System.TimeSpan.Subtract(TimeSpan ts)
   at OrleansDashboard.DashboardTelemetryConsumer.ComputeDelta(KeyValuePair`2 metric)
   at OrleansDashboard.DashboardTelemetryConsumer.<>c.<Flush>b__15_1(KeyValuePair`2 metric)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
   at OrleansDashboard.DashboardTelemetryConsumer.Flush()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()

**Comment by SebastianStehle** [comment]
PR is welcome ;)

**Comment by mhertis** [comment]
Ok, will try to make it next week ;)

**Comment by SebastianStehle** [comment]
It has been fixed now.
