### ISSUE TITLE
Dashboard lib firing constant warnings - System.ArgumentNullException: Value cannot be null. (Parameter 'key')

### ISSUE THREAD

**Issue by vlerouvillois-lixar** [OrleansContrib/OrleansDashboard#347]
I launch the silo from a fresh project (code is available here : https://github.com/vlerouvillois-lixar/orleans-dashboard-warnings).
After a minute, the output is flooded with these errors every second.
I don't think it is an expected behavior and I can't figure out how to get rid of these.

```
warn: Orleans.Grain.InvokeException[100322]
      Exception during Grain method call of message: OneWay S127.0.0.1:11111:382740049*cli/b6afe3a9@e4fbf594->S127.0.0.1:11111:382740049*grn/OrleansDashboard.Metrics.Grains.SiloGrain/0+127.0.0.1:11111@382740049@6bc7bfa5 InvokeMethodRequest OrleansDashboard.ISiloGrain:ReportCounters #525:
      Exc level 0: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at OrleansDashboard.Metrics.Grains.SiloGrain.ReportCounters(Immutable`1 reportCounters)
         at OrleansDashboard.OrleansCodeGenSiloGrainMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request)
         at Orleans.Runtime.GrainMethodInvoker.Invoke()
         at OrleansDashboard.Metrics.GrainProfilerFilter.Invoke(IIncomingGrainCallContext context)
         at Orleans.Runtime.GrainMethodInvoker.Invoke()
         at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message)
      System.ArgumentNullException: Value cannot be null. (Parameter 'key')
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at OrleansDashboard.Metrics.Grains.SiloGrain.ReportCounters(Immutable`1 reportCounters)
         at OrleansDashboard.OrleansCodeGenSiloGrainMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request)
         at Orleans.Runtime.GrainMethodInvoker.Invoke()
         at OrleansDashboard.Metrics.GrainProfilerFilter.Invoke(IIncomingGrainCallContext context)
         at Orleans.Runtime.GrainMethodInvoker.Invoke()
         at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message)
```
![image](https://user-images.githubusercontent.com/83468229/154359836-9b3eec81-5488-41a0-8114-740c277b4b34.png)

**Comment by richorama** [comment]
You appear to be using an older version of the dashboard. Could you try and upgrade to 3.6.1, as I think this has been fixed.

**Comment by vlerouvillois-lixar** [comment]
Thank you for getting back to me. You were right, latest 3.6.1 has the issue fixed. I actually tried before posting but my setup wasn't allowing me to run the app because I didn't have VS 22 with .NET 6 installed. Now I'm all up to speed!
