### ISSUE TITLE
Orleans 7: Calling DeactivateOnIdle from within OnActivateAsync is not supported

### ISSUE THREAD

**Issue by AndrewP-GH** [OrleansContrib/OrleansDashboard#380]
Hello!
I use dashboard v7.0.0 and faced error: 

Error activating grain "[Activation: S10.5.103.227:11111:29576505/silo/10.5.83.68:11111@29576535@8a03e98e186046ebba0cbed58c0cf664#GrainType=OrleansDashboard.Metrics.Grains.SiloGrain,OrleansDashboard Placement=LocalPlacementStrategy State=Activating]"
--

_System.InvalidOperationException_:
Calling DeactivateOnIdle from within OnActivateAsync is not supported
```
 at Orleans.Runtime.ActivationData.StartDeactivating(DeactivationReason reason) in /_/src/Orleans.Runtime/Catalog/ActivationData.cs:line 1362
   at Orleans.Grain.DeactivateOnIdle() in /_/src/Orleans.Core.Abstractions/Core/Grain.cs:line 123
   at OrleansDashboard.Metrics.Grains.SiloGrain.OnActivateAsync(CancellationToken cancellationToken)
   at Orleans.Internal.OrleansTaskExtentions.WithCancellation(Task taskToComplete, CancellationToken cancellationToken, String message) in /_/src/Orleans.Core/Async/TaskExtensions.cs:line 151
   at Orleans.Runtime.ActivationData.<ActivateAsync>g__CallActivateAsync|132_0(Dictionary`2 requestContextData, CancellationToken cancellationToken) in /_/src/Orleans.Runtime/Catalog/ActivationData.cs:line 1253
```

So are you aware of this problem?

**Comment by EquineSolutions** [comment]
I got the same problem when deploying to kubernetes, works fine locally

 Error activating grain [Activation: S10.2.1.35:12121:35726816/silo/10.2.0.32:12121@35726822@6a1310dc7772489dadd9b16ec0a48099#GrainType=OrleansDashboard.Metrics.Grains.SiloGrain,OrleansDashboard Placement=LocalPlacementStrategy State=Activating]
      System.InvalidOperationException: Calling DeactivateOnIdle from within OnActivateAsync is not supported
         at Orleans.Runtime.ActivationData.StartDeactivating(DeactivationReason reason) in /_/src/Orleans.Runtime/Catalog/ActivationData.cs:line 1345
         at Orleans.Runtime.ActivationData.Deactivate(DeactivationReason reason, Nullable`1 token) in /_/src/Orleans.Runtime/Catalog/ActivationData.cs:lin
