### ISSUE TITLE
Latest Orleans Version (7.2.0) fails to start when using the latest dashboard version.

### ISSUE THREAD

**Issue by NzKyle** [OrleansContrib/OrleansDashboard#402]
Just got done update all the base Orleans packages to the new `v7.2.0` - after doing so none of our Silos wanted to start up. I was seeing the following in the logs: 

```
Method not found: 'System.Threading.Tasks.ValueTask Orleans.Runtime.GrainReference.InvokeAsync(Orleans.Serialization.Invocation.IInvokable)'.

at OrleansCodeGen.OrleansDashboard.Proxy_IDashboardGrain.global::OrleansDashboard.IDashboardGrain.Init()
   at OrleansDashboard.Dashboard.ActivateDashboardGrainAsync()
   at OrleansDashboard.Dashboard.Execute(CancellationToken cancellationToken)
   at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct) in /_/src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs:line 134
   at Orleans.LifecycleSubject.OnStart(CancellationToken cancellationToken) in /_/src/Orleans.Core/Lifecycle/LifecycleSubject.cs:line 118
   at Orleans.Runtime.Scheduler.AsyncClosureWorkItem.Execute() in /_/src/Orleans.Runtime/Scheduler/ClosureWorkItem.cs:line 34
   at Orleans.Runtime.Silo.StartAsync(CancellationToken cancellationToken) in /_/src/Orleans.Runtime/Silo/Silo.cs:line 213
```

Everything behaves itself when I downgrade back to 7.1.2

**Comment by ReubenBond** [comment]
Apologies for breaking this. I didn't realize that we had introduced a binary break
