### ISSUE TITLE
Dashboard throws an exception when hosted in Service Fabric

### ISSUE THREAD

**Issue by richorama** [OrleansContrib/OrleansDashboard#47]
```
[2017-05-15 14:46:52.796 GMT    16    ERROR      101413    GrainTimer    127.0.0.1:30012]    !!!!!!!!!! Caught and ignored exception: System.NotImplementedException with mesagge: No membership table provider found for LivenessType=NotSpecified thrown from timer callback GrainTimer. TimerCallbackHandler:OrleansDashboard.DashboardGrain->System.Threading.Tasks.Task Callback(System.Object)    
Exc level 0: System.NotImplementedException: No membership table provider found for LivenessType=NotSpecified

Server stack trace: 
   at Orleans.Runtime.MembershipService.MembershipTableFactory.<GetMembershipTable>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Management.ManagementGrain.<GetHosts>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Management.ManagementGrain.<GetTotalActivationCount>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at OrleansDashboard.GrainProfiler.<InvokeInterceptor>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.InsideRuntimeClient.<Invoke>d__61.MoveNext()

Exception rethrown at [0]: 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OrleansDashboard.DashboardGrain.<Callback>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.GrainTimer.<ForwardToAsyncCallback>d__21.MoveNext()
```

**Comment by rikbosch** [comment]
I've been looking into a solution for this problem.

When hosted in ServiceFabric there is no membershiptable. SF components are used to determine liveliness of the silo's.

Details of a silo like hostname etc can be provided using a FabricClient, instead of the manager grain.

So, I would like to propose a ```ISiloDetailsProvider``` with one method ```Task<SiloDetails[]> GetSiloDetails()``` 

The default implementation should use the current logic. 

Silo's hosted in SF could provide a custom implementation.
