### ISSUE TITLE
Dashboard startup failing after Orleans 1.5 update

### ISSUE THREAD

**Issue by hermancombrink** [OrleansContrib/OrleansDashboard#62]
The log message below is produced after the latest orleans update to 1.5. However copying libuv.dll into the bin directory seems the solve to startup problem as a work around.

`xxx.Orleans.Silo.exe Error: 0 : [2017-07-10 23:51:17.297 GMT    27	ERROR  	10001	Dashboard	127.0.0.1:11111]	!!!!!!!!!! System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_loop_size()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.Init(Libuv uv)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Start(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at OrleansDashboard.Dashboard.<Init>d__15.MoveNext()
---> (Inner Exception #0) System.DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.NativeMethods.uv_loop_size()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.Init(Libuv uv)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(Object parameter)<---`

**Comment by DixonDs** [comment]
@hermancombrink Judging from similar issues reported (https://github.com/aspnet/KestrelHttpServer/issues/1625, https://github.com/aspnet/KestrelHttpServer/issues/1652), it looks like it could be related to the mismatch of the architecture of libuv.dll and the target project. Check the linked issues if any suggestions there help.

Otherwise, please provide some info. Do you target x64 or x86? How does your csproj look like where you host Orleans with the dashboard? A repro would be ideal.

**Comment by richorama** [comment]
I've seen this with other kestrel projects I've worked on, so I wonder if it's an upstream issue?

**Comment by shlomiw** [comment]
Hi, I'm having the same issue. How can you still Target AnyCPU where libuv.dll requires x86 or x64?

**Comment by vadimkorr** [comment]
Copying libuv.dll (from \packages\Libuv.1.9.1\runtimes\win7-x86\native\libuv.dll) to C:\Windows\System32\ solved my problem

**Comment by pherbel** [comment]
I got the same issue and my workaround was to create Asp.Net Core Service Fabric Service and it will bring the new project system. Then I just changed the project layout back and remove the Asp.Net core files.

It just works.

**Comment by dandago** [comment]
Same issue here on a brand new Orleans 1.5 Dev/Test Host.

**Comment by amccool** [comment]
is this a problem with the libuv nuget?
![image](https://user-images.githubusercontent.com/191144/31958185-cb3e5478-b8a5-11e7-8b0a-6e2d17315bf1.png)

**Comment by richorama** [comment]
I think there is, but it's beyond my understanding.
